"""HTML report emitter for Keen runs.

Produces a single self-contained ``report.html`` next to ``report.json`` and
``summary.md``. The HTML embeds every artifact (screenshots, annotated
overlays, per-component crops, token palette swatches) as base64 data URIs so
the file can be shared without any side-car directory.

Constraints:
  * Stdlib only — no Jinja2, no markdown library, no Pillow tricks beyond
    what report.py already uses.
  * No external HTTP requests in the rendered HTML (no CDN, no remote fonts).
  * All untrusted strings flow through ``html.escape`` before substitution.
  * The HTML must pass the same accessibility predicates Keen emits
    against any page (contrast >= 4.5:1, focus rings visible, landmarks).

The renderer is intentionally tolerant: missing artifacts (no screenshots,
no tokens, no captures) degrade to empty-state messaging rather than crash.
"""

from __future__ import annotations

import base64
import html
import logging
import re
from collections.abc import Iterable
from datetime import datetime, timezone
from pathlib import Path
from string import Template
from typing import Any

logger = logging.getLogger("keen.report.html")

# Severity ranking used for sortable table data-sort-value.
_SEVERITY_RANK = {"P0": 0, "P1": 1, "P2": 2}
_MAX_EMBED_IMAGE_BYTES = 8 * 1024 * 1024

_TEMPLATE_PATH = Path(__file__).parent / "templates" / "report.html.tmpl"


# ---------------------------------------------------------------------------
# Tiny markdown subset → HTML.
# ---------------------------------------------------------------------------


_BOLD_RE = re.compile(r"\*\*(.+?)\*\*", re.DOTALL)
_ITALIC_RE = re.compile(r"(?<![A-Za-z0-9_])_([^_\n]+?)_(?![A-Za-z0-9_])")
_CODE_RE = re.compile(r"`([^`\n]+?)`")
_LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)\s]+)\)")
_UL_RE = re.compile(r"^- (.*)$")
_HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)$")
_TABLE_ROW_RE = re.compile(r"^\|(.+)\|\s*$")
_TABLE_ALIGN_RE = re.compile(r"^\|[\s\-:|]+\|\s*$")


def _safe_link_url(raw: str) -> str:
    """Render ``[text](url)``-style links only for safe schemes.

    The summary.md is generated by us, but defense-in-depth: even if some
    upstream module ever embeds a hostile URL, only http/https/mailto/relative
    paths survive into the HTML; everything else collapses to ``#``.
    """
    lowered = raw.strip().lower()
    if lowered.startswith(("http://", "https://", "mailto:", "/", "#", "./", "../")):
        return html.escape(raw, quote=True)
    return "#"


def _apply_inline(text: str) -> str:
    """Apply inline markdown (bold/italic/code/link) to a pre-escaped string."""
    text = _CODE_RE.sub(lambda m: f"<code>{m.group(1)}</code>", text)
    # Render links AFTER code so backticks inside link text aren't garbled.
    text = _LINK_RE.sub(
        lambda m: f'<a href="{_safe_link_url(m.group(2))}">{m.group(1)}</a>',
        text,
    )
    text = _BOLD_RE.sub(lambda m: f"<strong>{m.group(1)}</strong>", text)
    text = _ITALIC_RE.sub(lambda m: f"<em>{m.group(1)}</em>", text)
    return text


def md_to_html(src: str, *, heading_offset: int = 0) -> str:
    r"""Render a narrow subset of markdown to HTML.

    Covers: ATX headings (# ## ### #### ##### ######), paragraphs separated by
    blank lines, ``**bold**``, ``_italic_``, ``\`inline code\```, fenced code
    blocks (```), bullet lists (``- ``), GFM-style tables, and
    ``[link text](url)`` inline links.

    Not a full CommonMark implementation. The summary.md is generated by us,
    so we control the input shape — see render_summary in report.py.

    Input is HTML-escaped via ``html.escape`` so no arbitrary HTML passes
    through (defense against any pre-injected markdown that survived
    ``_sanitize.py``).

    ``heading_offset`` shifts every heading down by N levels (clamped to h6) so
    the embedded markdown doesn't compete with the page's own ``<h1>``. Set to
    1 when injecting summary.md into a section that already has its own
    ``<h2>`` heading.
    """
    if not src:
        return ""

    # Escape the whole input first so any < > & in the source becomes inert.
    # Inline rules then re-inject only the specific tags we want.
    escaped = html.escape(src, quote=False)
    lines = escaped.split("\n")

    out: list[str] = []
    in_code = False
    code_buf: list[str] = []
    in_list = False
    in_para: list[str] = []
    in_table = False
    table_buf: list[list[str]] = []
    table_aligns: list[str] = []
    table_header_done = False

    def flush_para() -> None:
        nonlocal in_para
        if in_para:
            text = " ".join(in_para).strip()
            if text:
                out.append(f"<p>{_apply_inline(text)}</p>")
            in_para = []

    def flush_list() -> None:
        nonlocal in_list
        if in_list:
            out.append("</ul>")
            in_list = False

    def flush_table() -> None:
        nonlocal in_table, table_buf, table_aligns, table_header_done
        if in_table and table_buf:
            out.append("<table>")
            if table_header_done and table_buf:
                # First row is header.
                out.append("<thead><tr>")
                for cell in table_buf[0]:
                    out.append(f"<th>{_apply_inline(cell.strip())}</th>")
                out.append("</tr></thead>")
                body = table_buf[1:]
            else:
                body = table_buf
            if body:
                out.append("<tbody>")
                for row in body:
                    out.append("<tr>")
                    for cell in row:
                        out.append(f"<td>{_apply_inline(cell.strip())}</td>")
                    out.append("</tr>")
                out.append("</tbody>")
            out.append("</table>")
        in_table = False
        table_buf = []
        table_aligns = []
        table_header_done = False

    def flush_all() -> None:
        flush_para()
        flush_list()
        flush_table()

    for raw_line in lines:
        line = raw_line.rstrip()

        # Fenced code blocks: ``` start/end.
        if line.startswith("```"):
            if in_code:
                out.append("<pre><code>" + "\n".join(code_buf) + "</code></pre>")
                code_buf = []
                in_code = False
            else:
                flush_all()
                in_code = True
            continue
        if in_code:
            code_buf.append(line)
            continue

        # Tables (GFM).
        m_row = _TABLE_ROW_RE.match(line)
        m_align = _TABLE_ALIGN_RE.match(line)
        if m_row and m_align and in_table and len(table_buf) == 1:
            # Alignment row right after a header row — mark header as done.
            table_aligns = [c.strip() for c in m_row.group(1).split("|")]
            table_header_done = True
            continue
        if m_row:
            if not in_table:
                flush_all()
                in_table = True
            cells = list(line.strip("|").split("|"))
            table_buf.append(cells)
            continue
        if in_table:
            flush_table()

        # Headings.
        m_h = _HEADING_RE.match(line)
        if m_h:
            flush_all()
            level = min(6, len(m_h.group(1)) + heading_offset)
            content = _apply_inline(m_h.group(2))
            out.append(f"<h{level}>{content}</h{level}>")
            continue

        # Bullet list.
        m_ul = _UL_RE.match(line)
        if m_ul:
            flush_para()
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append(f"<li>{_apply_inline(m_ul.group(1))}</li>")
            continue

        # Horizontal rule.
        if line.strip() in {"---", "***", "___"}:
            flush_all()
            out.append("<hr>")
            continue

        # Blank line ends paragraphs/lists.
        if not line.strip():
            flush_para()
            flush_list()
            flush_table()
            continue

        # Default: paragraph.
        flush_list()
        in_para.append(line.strip())

    # End of input — close any open container.
    if in_code:
        out.append("<pre><code>" + "\n".join(code_buf) + "</code></pre>")
    flush_all()
    return "\n".join(out)


# ---------------------------------------------------------------------------
# Image embedding helpers.
# ---------------------------------------------------------------------------


def _encode_image(path: Path) -> str | None:
    """Read PNG at ``path``, return ``data:image/png;base64,...`` or None.

    Defensive: large or unreadable files return ``None`` so the renderer can
    fall back to an empty-state placeholder.
    """
    try:
        size = path.stat().st_size
        if size > _MAX_EMBED_IMAGE_BYTES:
            logger.warning(
                "refusing to embed %s: %d bytes exceeds the %d-byte limit; use linked images",
                path,
                size,
                _MAX_EMBED_IMAGE_BYTES,
            )
            return None
        data = path.read_bytes()
    except OSError as e:
        logger.warning("could not read %s for embedding: %s", path, e)
        return None
    encoded = base64.b64encode(data).decode("ascii")
    # Crude content-type sniffing — all our screenshots are PNG, but be robust.
    if data[:4] == b"\x89PNG":
        ct = "image/png"
    elif data[:3] in (b"\xff\xd8\xff", b"GIF"):
        ct = "image/jpeg" if data[:3] == b"\xff\xd8\xff" else "image/gif"
    elif data[:6] in (b"RIFF\x00\x00", b"WEBPVP"):
        ct = "image/webp"
    else:
        ct = "image/png"
    return f"data:{ct};base64,{encoded}"


def _image_src(captures_dir: Path, rel_path: str | None, *, link_images: bool) -> str | None:
    """Resolve a relative image path into either a base64 data URI or a
    sandboxed relative-path string.

    ``rel_path`` may be ``None`` or refer to a file that no longer exists; both
    cases return ``None`` so the caller can omit the figure entirely.
    """
    if not rel_path:
        return None
    captures_root = captures_dir.resolve()
    target = (captures_dir / rel_path).resolve()
    try:
        target.relative_to(captures_root)
    except ValueError:
        logger.warning("blocked path traversal: %s outside %s", target, captures_root)
        return None
    if not target.exists():
        return None
    if link_images:
        # Use the relative path verbatim (it's already constrained to
        # captures_root). Escape for HTML attribute safety.
        return html.escape(rel_path, quote=True)
    return _encode_image(target)


# ---------------------------------------------------------------------------
# Section renderers.
# ---------------------------------------------------------------------------


def _render_findings_table(top_findings: Iterable[dict[str, Any]]) -> str:
    findings = list(top_findings)
    if not findings:
        return '<p class="empty" role="status">No findings to display.</p>'
    rows: list[str] = []
    for f in findings:
        finding_id = str(f.get("finding_id") or "")
        annotation_id = str(f.get("annotation_id") or "")
        sev = str(f.get("severity", "P2"))
        sev_rank = _SEVERITY_RANK.get(sev, 9)
        pid = str(f.get("predicate_id", ""))
        kind = str(f.get("component_kind", ""))
        viewport = str(f.get("viewport", "") or "")
        state = str(f.get("state", "") or "")
        msg = str(f.get("message", ""))
        crop = str(f.get("crop_path", "") or "")
        component_idx = f.get("component_index")
        target_id = (
            _component_anchor(viewport, state, component_idx) if component_idx is not None else None
        )
        loc = f"{viewport}/{state}" if viewport or state else ""
        link_html = ""
        if annotation_id:
            link_html += (
                f' <a class="evidence-link" href="#annotation-{html.escape(annotation_id, quote=True)}">'
                f"locate {html.escape(annotation_id)}</a>"
            )
        if target_id:
            # Visible label "view" must appear in the accessible name (WCAG 2.5.3
            # Label in Name). Putting "view" first satisfies the speech-input
            # check and the longer phrase still gives context to screen readers.
            link_html += (
                f' <a class="row-link" href="#{html.escape(target_id, quote=True)}" '
                f'aria-label="view {html.escape(kind)} component">view</a>'
            )
        elif crop:
            link_html += f" <code>{html.escape(crop)}</code>"
        row_id = f' id="{html.escape(finding_id, quote=True)}"' if finding_id else ""
        rows.append(
            f"<tr{row_id}>"
            f'<td data-sort-value="{sev_rank}">'
            f'<span class="badge badge-{html.escape(sev)}" aria-label="severity {html.escape(sev)}">{html.escape(sev)}</span>'
            "</td>"
            f'<td data-sort-value="{html.escape(pid)}"><code>{html.escape(pid)}</code></td>'
            f'<td data-sort-value="{html.escape(kind)}">{html.escape(kind)}</td>'
            f'<td data-sort-value="{html.escape(loc)}">{html.escape(loc)}</td>'
            f"<td>{html.escape(msg)}{link_html}</td>"
            "</tr>"
        )
    head = (
        "<thead><tr>"
        '<th data-sort-type="number" scope="col"><button type="button" class="sort-button">'
        'Severity<span class="sort-indicator" aria-hidden="true"></span></button></th>'
        '<th scope="col"><button type="button" class="sort-button">'
        'Predicate<span class="sort-indicator" aria-hidden="true"></span></button></th>'
        '<th scope="col"><button type="button" class="sort-button">'
        'Component<span class="sort-indicator" aria-hidden="true"></span></button></th>'
        '<th scope="col"><button type="button" class="sort-button">'
        'Location<span class="sort-indicator" aria-hidden="true"></span></button></th>'
        '<th scope="col"><button type="button" class="sort-button">'
        'Message<span class="sort-indicator" aria-hidden="true"></span></button></th>'
        "</tr></thead>"
    )
    body = "<tbody>" + "".join(rows) + "</tbody>"
    return f'<table class="findings" aria-label="Candidate findings, sortable">{head}{body}</table>'


def _render_gallery(
    captures: list[dict[str, Any]],
    annotated: dict[str, str],
    annotations: dict[str, list[dict[str, Any]]],
    captures_dir: Path,
    *,
    link_images: bool,
) -> str:
    if not captures:
        return '<p class="empty" role="status">No screenshots captured.</p>'
    figs: list[str] = []
    for idx, cap in enumerate(captures):
        viewport = str(cap.get("viewport", "") or "")
        state = str(cap.get("state", "") or "")
        screen_rel = cap.get("screen_path")
        raw_src = _image_src(captures_dir, screen_rel, link_images=link_images)
        # Look up annotated by stem.
        annot_src: str | None = None
        if screen_rel:
            stem = Path(screen_rel).stem
            annot_rel = annotated.get(stem)
            if annot_rel:
                annot_src = _image_src(captures_dir, annot_rel, link_images=link_images)
        else:
            stem = ""
        marker_entries = list(annotations.get(stem) or [])

        if not raw_src and not annot_src:
            continue

        manual = cap.get("manual_review_needed", False)
        manual_tag = (
            ' <span class="badge badge-P1" aria-label="Manual review needed">manual</span>'
            if manual
            else ""
        )
        wrap_id = f"shot-{idx}"
        figure_parts: list[str] = []
        figure_parts.append(f'<figure id="screen-{idx}">')
        figure_parts.append(
            "<figcaption>"
            '<span class="screen-label">'
            f'<span class="vp-label">{html.escape(viewport)}'
            f"{(' / ' + html.escape(state)) if state else ''}{manual_tag}</span>"
            f'<span class="screen-count">{len(marker_entries)} mapped priorit'
            f"{'y' if len(marker_entries) == 1 else 'ies'}</span>"
            "</span>"
            '<span class="screen-actions">'
        )
        if annot_src and raw_src:
            figure_parts.append(
                f'<button type="button" class="toggle-btn" data-toggle-target="{wrap_id}" '
                'aria-pressed="false">Show evidence map</button>'
            )
        figure_parts.append(
            f'<button type="button" class="inspect-btn" data-inspect-target="{wrap_id}" '
            'aria-pressed="false">Inspect detail</button>'
        )
        if raw_src:
            figure_parts.append(
                f'<a class="full-image-link" href="{raw_src}" target="_blank" '
                'rel="noopener">Open image</a>'
            )
        figure_parts.append("</span>")
        figure_parts.append("</figcaption>")
        figure_parts.append(f'<div class="img-wrap" id="{wrap_id}">')
        # Default visible: raw screenshot; annotated hidden until toggled.
        if raw_src:
            figure_parts.append(
                f'<img data-variant="raw" src="{raw_src}" '
                f'alt="screenshot of {html.escape(viewport)} {html.escape(state)}" loading="lazy">'
            )
        if annot_src:
            figure_parts.append(
                f'<img data-variant="annotated" src="{annot_src}" '
                f'alt="annotated screenshot of {html.escape(viewport)} {html.escape(state)} '
                'with bounding boxes" hidden loading="lazy">'
            )
        figure_parts.append("</div>")
        if marker_entries:
            figure_parts.append('<ol class="annotation-key" aria-label="Mapped priority findings">')
            for marker in marker_entries:
                annotation_id = str(marker.get("id") or "")
                severity = str(marker.get("severity") or "P1")
                predicates = ", ".join(str(value) for value in (marker.get("predicate_ids") or []))
                message = str(marker.get("message") or "")
                finding_ids = marker.get("finding_ids") or []
                href = f"#{finding_ids[0]}" if finding_ids else "#findings"
                figure_parts.append(
                    f'<li id="annotation-{html.escape(annotation_id, quote=True)}">'
                    f'<a href="{html.escape(href, quote=True)}">'
                    f'<span class="annotation-marker badge-{html.escape(severity)}">'
                    f"{html.escape(annotation_id)}</span>"
                    '<span class="annotation-copy">'
                    f"<strong>{html.escape(severity)} · {html.escape(predicates)}</strong>"
                    f"<span>{html.escape(message)}</span>"
                    "</span></a></li>"
                )
            figure_parts.append("</ol>")
        figure_parts.append("</figure>")
        figs.append("".join(figure_parts))
    if not figs:
        return '<p class="empty" role="status">No screenshots could be embedded.</p>'
    return '<div class="gallery">' + "".join(figs) + "</div>"


def _render_components(
    components: list[dict[str, Any]],
    top_findings: list[dict[str, Any]],
    captures_dir: Path,
    *,
    link_images: bool,
    limit: int = 24,
) -> str:
    flagged = [c for c in components if c.get("findings")]
    if not flagged:
        return '<p class="empty" role="status">No flagged components.</p>'

    by_key = {
        (str(component.get("capture_path") or ""), component.get("index")): component
        for component in flagged
    }
    selected: list[dict[str, Any]] = []
    selected_keys: set[tuple[str, Any]] = set()

    def add(component: dict[str, Any]) -> None:
        key = (str(component.get("capture_path") or ""), component.get("index"))
        if key not in selected_keys and len(selected) < limit:
            selected.append(component)
            selected_keys.add(key)

    # Every component linked from the bounded findings table must exist in the
    # evidence section. This keeps table links truthful while avoiding a
    # hundred-card appendix dominated by one repeated heuristic.
    for finding in top_findings:
        key = (
            str(finding.get("capture_path") or ""),
            finding.get("component_index"),
        )
        component = by_key.get(key)
        if component is not None:
            add(component)

    severity_rank = {"P0": 0, "P1": 1, "P2": 2}

    def card_rank(component: dict[str, Any]) -> tuple[int, str, str, int]:
        findings = component.get("findings") or []
        best = min(
            (severity_rank.get(str(finding.get("severity") or "P2"), 9) for finding in findings),
            default=9,
        )
        predicates = sorted(str(finding.get("predicate_id") or "") for finding in findings)
        return (
            best,
            predicates[0] if predicates else "",
            str(component.get("capture_path") or ""),
            int(component.get("index") or 0),
        )

    predicate_counts: dict[str, int] = {}
    for component in sorted(flagged, key=card_rank):
        if len(selected) >= limit:
            break
        predicates = {
            str(finding.get("predicate_id") or "") for finding in (component.get("findings") or [])
        }
        if predicates and all(predicate_counts.get(pid, 0) >= 3 for pid in predicates):
            continue
        before = len(selected)
        add(component)
        if len(selected) > before:
            for predicate_id in predicates:
                predicate_counts[predicate_id] = predicate_counts.get(predicate_id, 0) + 1

    cards: list[str] = []
    for c in selected:
        idx = c.get("index")
        kind = str(c.get("component_kind", ""))
        viewport = str(c.get("viewport", "") or "")
        state = str(c.get("state", "") or "")
        box = c.get("box", {}) or {}
        crop_rel = c.get("crop_path")
        crop_src = _image_src(captures_dir, crop_rel, link_images=link_images)
        anchor = _component_anchor(viewport, state, idx) if idx is not None else ""
        bx, by = box.get("x", 0), box.get("y", 0)
        bw, bh = box.get("w", 0), box.get("h", 0)
        try:
            bx_s = f"{float(bx):.0f}"
            by_s = f"{float(by):.0f}"
            bw_s = f"{float(bw):.0f}"
            bh_s = f"{float(bh):.0f}"
        except (TypeError, ValueError):
            bx_s = by_s = bw_s = bh_s = "?"
        findings_items: list[str] = []
        for f in c.get("findings", []) or []:
            sev = str(f.get("severity", "P2"))
            msg = str(f.get("message", ""))
            pid = str(f.get("predicate_id", ""))
            findings_items.append(
                f'<li><span class="badge badge-{html.escape(sev)}" '
                f'aria-label="severity {html.escape(sev)}">{html.escape(sev)}</span> '
                f"<code>{html.escape(pid)}</code> — {html.escape(msg)}</li>"
            )
        img_html = ""
        if crop_src:
            img_html = (
                f'<img src="{crop_src}" alt="crop of {html.escape(kind)} component" loading="lazy">'
            )
        anchor_attr = f' id="{html.escape(anchor, quote=True)}"' if anchor else ""
        card = (
            f'<article class="component-card"{anchor_attr}>'
            f"{img_html}"
            f'<div class="ckind">{html.escape(kind)}</div>'
            f'<div class="cbox">{html.escape(viewport)}/{html.escape(state)} '
            f"@ {bx_s},{by_s} {bw_s}×{bh_s}</div>"
            f'<ul class="cfind">{"".join(findings_items)}</ul>'
            "</article>"
        )
        cards.append(card)
    note = (
        f'<p class="evidence-summary">Showing {len(selected)} representative components '
        f"from {len(flagged)} flagged. The complete inventory remains in "
        "<code>report.json</code>.</p>"
        if len(selected) < len(flagged)
        else ""
    )
    return note + '<div class="component-list">' + "".join(cards) + "</div>"


def _component_anchor(viewport: str, state: str, index: Any) -> str:
    """Return a capture-scoped, HTML-safe anchor for a component."""
    raw = f"component-{viewport}-{state}-{index}".lower()
    return re.sub(r"[^a-z0-9_-]+", "-", raw).strip("-")


def _render_tokens(tokens: dict[str, Any]) -> str:
    if not tokens:
        return '<p class="empty" role="status">No tokens extracted.</p>'
    parts: list[str] = []

    colors = tokens.get("colors") or {}
    fg = colors.get("foreground") or []
    bg = colors.get("background") or []

    def color_swatches(label: str, items: list[dict[str, Any]]) -> str:
        if not items:
            return ""
        swatches: list[str] = []
        for entry in items[:16]:
            val = str(entry.get("value", "") or "")
            count = entry.get("count", 0)
            # Only inject color values that look safe (rgb()/rgba()/#hex/named).
            safe = bool(
                re.match(
                    r"^(?:#[0-9a-fA-F]{3,8}|rgb\(\s*[\d., %]+\s*\)|rgba\(\s*[\d., %]+\s*\)|[a-zA-Z]+)$",
                    val.strip(),
                )
            )
            chip_style = f"background:{val}" if safe and val else "background:transparent"
            swatches.append(
                '<div class="swatch">'
                f'<span class="chip" style="{html.escape(chip_style, quote=True)}" aria-hidden="true"></span>'
                f"<span>{html.escape(val)}</span>"
                f'<span class="count">x{int(count) if isinstance(count, (int, float)) else 0}</span>'
                "</div>"
            )
        return f'<h3>{html.escape(label)}</h3><div class="swatches">{"".join(swatches)}</div>'

    parts.append(color_swatches("Foreground colors", fg))
    parts.append(color_swatches("Background colors", bg))

    # Type scale.
    type_block = tokens.get("type") or {}
    sizes = type_block.get("sizes_px") or []
    if sizes:
        rows: list[str] = []
        for entry in sizes[:12]:
            val = entry.get("value")
            count = entry.get("count", 0)
            if not isinstance(val, (int, float, str)):
                continue
            try:
                px = float(val)
            except (TypeError, ValueError):
                continue
            # Cap rendered sample at 48px so wild outliers don't break layout.
            sample_size = min(max(px, 10), 48)
            rows.append(
                '<div class="scale-row">'
                f'<span class="sample" style="font-size:{sample_size:.0f}px">Aa</span>'
                f'<span class="meta">{px:.0f}px '
                f'<span class="count">x{int(count) if isinstance(count, (int, float)) else 0}</span></span>'
                "</div>"
            )
        if rows:
            parts.append("<h3>Type scale</h3>" + "".join(rows))

    # Spacing + radii.
    shape = tokens.get("shape") or {}
    radii = shape.get("border_radii_px") or []
    spacing = (tokens.get("spacing") or {}).get("values_px") or []

    def numeric_list(label: str, items: list[dict[str, Any]]) -> str:
        if not items:
            return ""
        swatches: list[str] = []
        for entry in items[:24]:
            val = entry.get("value")
            count = entry.get("count", 0)
            if not isinstance(val, (int, float, str)):
                continue
            try:
                px = float(val)
            except (TypeError, ValueError):
                continue
            swatches.append(
                '<div class="swatch">'
                f"<span>{px:.0f}px</span>"
                f'<span class="count">x{int(count) if isinstance(count, (int, float)) else 0}</span>'
                "</div>"
            )
        return f'<h3>{html.escape(label)}</h3><div class="swatches">{"".join(swatches)}</div>'

    parts.append(numeric_list("Border radii", radii))
    parts.append(numeric_list("Spacing values", spacing))

    diag = tokens.get("diagnostics") or {}
    if diag:
        diagnostic_rows: list[str] = []
        for k, v in diag.items():
            diagnostic_rows.append(f"<dt>{html.escape(str(k))}</dt><dd>{html.escape(str(v))}</dd>")
        parts.append(
            "<h3>Diagnostics</h3>" + f'<dl class="kv-grid">{"".join(diagnostic_rows)}</dl>'
        )

    rendered = "".join(p for p in parts if p)
    if not rendered:
        return '<p class="empty" role="status">No tokens extracted.</p>'
    return rendered


# ---------------------------------------------------------------------------
# Top-level renderer.
# ---------------------------------------------------------------------------


def _redacted_url_for_display(captures: list[dict[str, Any]]) -> str:
    """Pick the first capture's URL, already redacted by sanitize_capture_meta."""
    for cap in captures:
        url = cap.get("url")
        if url:
            return str(url)
    return ""


def _display_title(captures: list[dict[str, Any]]) -> str:
    """Prefer the document title; shorten local-file fallbacks to a filename."""
    for cap in captures:
        title = str(cap.get("title", "") or "").strip()
        if title:
            return title
    raw = _redacted_url_for_display(captures)
    if raw.startswith("file://"):
        return Path(raw.removeprefix("file://")).name or "Local interface"
    return raw or "Keen review"


def _render_verdict(
    report: dict[str, Any],
    *,
    captures: list[dict[str, Any]],
    summary_md: str,
) -> str:
    """Render a decision-first overview without repeating later evidence chapters."""
    score = report.get("score") or {}
    if not score and summary_md:
        return md_to_html(summary_md, heading_offset=2)

    counts = score.get("counts") or {}

    def count(severity: str) -> int:
        value = counts.get(severity, 0)
        return int(value) if isinstance(value, (int, float)) else 0

    p0, p1, p2 = count("P0"), count("P1"), count("P2")
    coverage = report.get("coverage") or {}
    complete = bool(coverage.get("complete", True))
    capture_status = "complete" if complete else "provisional"
    total = p0 + p1 + p2
    signal_copy = (
        f"The harness found {total} deterministic candidate signal{'s' if total != 1 else ''}. "
        "They locate evidence; they do not decide whether the product is beautiful, coherent, or ready."
    )
    guidance = (
        "Use project direction and rendered context to assign user impact and final priority."
    )
    return (
        '<div class="verdict-lead">'
        '<p class="verdict-kicker">Automated evidence</p>'
        f'<p class="verdict-copy">{html.escape(signal_copy)}</p>'
        "</div>"
        '<dl class="verdict-facts">'
        f"<div><dt>P0 candidates</dt><dd>{p0}</dd></div>"
        f"<div><dt>P1 candidates</dt><dd>{p1}</dd></div>"
        f"<div><dt>P2 candidates</dt><dd>{p2}</dd></div>"
        f"<div><dt>Capture coverage</dt><dd>{len(captures)} / {html.escape(capture_status)}</dd></div>"
        "</dl>"
        f'<p class="verdict-guidance">{html.escape(guidance)}</p>'
        '<a class="verdict-link" href="#findings">Inspect candidate evidence <span aria-hidden="true">→</span></a>'
    )


def _iso_now() -> str:
    """Return current UTC ISO-8601 timestamp suitable for the report header."""
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def render_report(
    report: dict[str, Any],
    *,
    captures_dir: Path,
    summary_md: str,
    link_images: bool = False,
) -> str:
    """Render the full ``report.html`` string.

    Parameters
    ----------
    report:
        The dict returned by ``report.compose`` (same shape as ``report.json``).
    captures_dir:
        The directory the run wrote into. Image paths are resolved relative to
        it; traversal outside is blocked.
    summary_md:
        The summary as produced by ``report.render_summary`` — gets rendered
        through the tiny markdown converter into ``<div class="summary-block">``.
    link_images:
        When True, image ``src`` attributes are emitted as relative paths
        (e.g. ``./screens/desktop-default.png``). When False (default), images
        are inlined as base64 ``data:`` URIs so ``report.html`` is fully
        self-contained.
    """
    captures = list(report.get("captures") or [])
    score = report.get("score") or {}
    title = _display_title(captures)

    summary_html = _render_verdict(report, captures=captures, summary_md=summary_md)
    findings_html = _render_findings_table(report.get("top_findings") or [])
    gallery_html = _render_gallery(
        captures,
        dict(report.get("annotated_overviews") or {}),
        dict(report.get("annotations") or {}),
        captures_dir,
        link_images=link_images,
    )
    components_html = _render_components(
        list(report.get("components") or []),
        list(report.get("top_findings") or []),
        captures_dir,
        link_images=link_images,
    )
    tokens_html = _render_tokens(dict(report.get("tokens") or {}))

    target_system = report.get("target_system") or "(none)"
    grade = score.get("grade") or "?"
    damage_val = score.get("score")
    damage = "—" if damage_val is None else f"{damage_val}"

    template_text = _TEMPLATE_PATH.read_text(encoding="utf-8")
    tmpl = Template(template_text)
    return tmpl.substitute(
        title=html.escape(str(title)),
        captured_at=html.escape(_iso_now()),
        grade=html.escape(str(grade)),
        damage=html.escape(damage),
        target_system=html.escape(str(target_system)),
        summary_html=summary_html,
        findings_table_html=findings_html,
        gallery_html=gallery_html,
        components_html=components_html,
        tokens_html=tokens_html,
    )


def write_report(
    report: dict[str, Any],
    captures_dir: Path,
    summary_md: str,
    *,
    link_images: bool = False,
) -> Path:
    """Render and write ``report.html`` into ``captures_dir``.

    Returns the path written. Errors are logged and swallowed: the HTML report
    is a convenience; if rendering blows up, the run still produces JSON and
    markdown.
    """
    out_path = Path(captures_dir) / "report.html"
    try:
        html_str = render_report(
            report,
            captures_dir=Path(captures_dir),
            summary_md=summary_md,
            link_images=link_images,
        )
        out_path.write_text(html_str, encoding="utf-8")
    except Exception:
        logger.exception("html report generation failed; report.html not written")
        # Best-effort: do not propagate. The caller already has JSON/MD.
        return out_path
    return out_path
